### ISSUE TITLE
Build requirements?

### ISSUE THREAD

**Issue by msakrejda** [rowan-sl/trifit#1]
I tried building from source and I get

---
<details>
<summary>
error: linking with `clang` failed: exit status: 1
</summary>
  |
  = note: "clang" "-m64" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.0.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.1.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.10.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.11.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.12.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.13.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.14.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.15.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.2.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.3.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.4.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.5.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.6.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.7.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.8.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.build_script_build.9fe563ac-cgu.9.rcgu.o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77.4jxiy5kn0d3yhpfs.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/trifit/target/debug/deps" "-L" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-fad6565a4a24ca7c.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-7333b08131ad69c0.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-8fd2f24f083ee871.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-63c9c6ed2f71b398.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-ac6764d7272415e2.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-a92344eafcadd40d.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-a53256cbf12c5e40.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-d076501d614ddd5d.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-dc343399b5db12bf.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-8e60620ba8892302.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-c52b4818022f32c3.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-5ad6d336de25263f.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3b7b15eacc8412be.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-9166aee941371fa5.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-e869a247063ed69a.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-cd90985afc868a6d.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2e57f9284f7a2443.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/maciek/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/trifit/target/debug/build/serde-83cccee93f08ce77/build_script_build-83cccee93f08ce77" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-fuse-ld=lld"
  = note: clang: error: invalid linker name in argument '-fuse-ld=lld'
</details>
error: build failed

---

Is a particular clang or rustc version required?

```
maciek@whimbrel:/tmp/trifit$ clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
maciek@whimbrel:/tmp/trifit$ rustc --version
rustc 1.60.0-nightly (09cb29c64 2022-02-15)
```

**Comment by ashsystems** [comment]
it seems like I had forgotten to gitignore a config file that told rust to use clang/lld as a linker, which would fail on systems without it properly installed. (also apparently if you include `fixes #<number>` in a commit message it auto-closes the issue?)

**Comment by msakrejda** [comment]
Thanks! But now I get a different error:

```
maciek@whimbrel:/tmp/trifit$ cargo build
error: failed to load manifest for workspace member `/tmp/trifit/v2`

Caused by:
  failed to read `/tmp/trifit/v2/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
Re:
>also apparently if you include fixes #<number> in a commit message it auto-closes the issue?)

Yeah, they've had this forever (and it even usually does what you want): https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by ashsystems** [comment]
oh :facepalm: it *should* be fixed now tho.

**Comment by msakrejda** [comment]
I was still getting some errors with my old nightly from February:

```
   Compiling trifit v0.4.0 (/tmp/trifit)
error[E0658]: deriving `Default` on enums is experimental
   --> src/main.rs:110:41
    |
110 | #[derive(Debug, Clone, Copy, ValueEnum, Default)]
    |                                         ^^^^^^^
    |
    = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
    = help: add `#![feature(derive_default_enum)]` to the crate attributes to enable
    = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'total_cmp'
   --> src/scoring/mod.rs:259:37
    |
259 |                 .sorted_by(|a, b| b.total_cmp(a))
    |                                     ^^^^^^^^^
    |
    = note: see issue #72599 <https://github.com/rust-lang/rust/issues/72599> for more information
    = help: add `#![feature(total_cmp)]` to the crate attributes to enable

error[E0599]: no method named `is_finished` found for reference `&std::thread::JoinHandle<()>` in the current scope
   --> src/main.rs:462:28
    |
462 |             if proc_thread.is_finished() {
    |                            ^^^^^^^^^^^ method not found in `&std::thread::JoinHandle<()>`

Some errors have detailed explanations: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `trifit` due to 3 previous errors
```

But I updated to a new nightly, and it seems to work now! It might be handy to specify the required version in the README.

**Comment by ashsystems** [comment]
oh yeah good idea
